### ISSUE TITLE
what():  RtApi::openStream: output device parameter value is invalid.

### ISSUE THREAD

**Issue by callimero** [Quinny/GuitarEffects#10]
Not sure what is the problem. I see my audio interface and can record from it.

pi@raspberrypi:~/GuitarEffects/web $ sudo ../bin/server 
device ID = 0
device name: PulseAudio
: maximum output channels = 2
: maximum input channels = 2
Native format: 26
Sample rate 48000
terminate called after throwing an instance of 'RtAudioError'
  what():  RtApi::openStream: output device parameter value is invalid.
Aborted
pi@raspberrypi:~/GuitarEffects/web $

**Comment by Quinny** [comment]
Did you modify the main file to change the input and output device indices to match yours? They are currently just static defaults (been meaning to fix that at some point…)

**Comment by Quinny** [comment]
Yeah I just doubled checked, the defaults are 1,1 try changing it to 0,0 on this line and the next: https://github.com/Quinny/GuitarEffects/blob/660fe15a8f697e22a26feb7a0bce068824c3de44/web/main.cpp#L75-L76

(please leave this issue open and I’ll use it for the real fix which will be auto finding the audio interface)

**Comment by callimero** [comment]
> Did you modify the main file to change the input and output device indices to match yours? They are currently just static defaults (been meaning to fix that at some point…)

Of course not! ;) Sorry.

**Comment by callimero** [comment]
With both 0 I got a black Visualizer Window with

`RtApiPulse::callbackEvent: audio write error, Invalid argument.
`
in the terminal repeating.

Then I used

`pacmd list-cards`

to find the indices. And did:

`AudioTransformer at(transform,
                      /* input_device_index= */ in_debug_mode ? 0 : 0,
                      /* output_device_index= */ in_debug_mode ? 2 : 2,
                      /* treat_input_as_mono= */ in_debug_mode ? 1 : 1);`

This resulted in:

`device ID = 0
device name: PulseAudio
: maximum output channels = 2
: maximum input channels = 2
Native format: 26
Sample rate 48000
terminate called after throwing an instance of 'RtAudioError'
  what():  RtApi::openStream: output device parameter value is invalid.
Aborted
`

pi@raspberrypi:~/GuitarEffects/web $ pacmd list-cards
3 card(s) available.
    index: 0
	name: <alsa_card.usb-Hercules_Rocksmith_USB_Guitar_Adapter-00>
	driver: <module-alsa-card.c>
	owner module: 6
	properties:
		alsa.card = "2"
		alsa.card_name = "Rocksmith USB Guitar Adapter"
		alsa.long_card_name = "Hercules Rocksmith USB Guitar Adapter at usb-0000:01:00.0-1.4, full speed"
		alsa.driver_name = "snd_usb_audio"
		device.bus_path = "platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.4:1.0"
		sysfs.path = "/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.4/1-1.4:1.0/sound/card2"
		udev.id = "usb-Hercules_Rocksmith_USB_Guitar_Adapter-00"
		device.bus = "usb"
		device.vendor.id = "12ba"
		device.vendor.name = "Licensed by Sony Computer Entertainment America"
		device.product.id = "00ff"
		device.product.name = "Rocksmith Guitar Adapter"
		device.serial = "Hercules_Rocksmith_USB_Guitar_Adapter"
		device.string = "2"
		device.description = "Rocksmith Guitar Adapter"
		module-udev-detect.discovered = "1"
		device.icon_name = "audio-card-usb"
	profiles:
		input:analog-mono: Analog Mono Input (priority 7, available: unknown)
		off: Off (priority 0, available: unknown)
	active profile: <input:analog-mono>
	sources:
		alsa_input.usb-Hercules_Rocksmith_USB_Guitar_Adapter-00.analog-mono/#0: Rocksmith Guitar Adapter Analog Mono
	ports:
		analog-input-mic: Microphone (priority 8700, latency offset 0 usec, available: unknown)
			properties:
				device.icon_name = "audio-input-microphone"
    index: 1
	name: <alsa_card.platform-bcm2835_audio>
	driver: <module-alsa-card.c>
	owner module: 7
	properties:
		alsa.card = "0"
		alsa.card_name = "bcm2835 HDMI 1"
		alsa.long_card_name = "bcm2835 HDMI 1"
		alsa.driver_name = "snd_bcm2835"
		device.bus_path = "platform-bcm2835_audio"
		sysfs.path = "/devices/platform/soc/fe00b840.mailbox/bcm2835_audio/sound/card0"
		device.form_factor = "internal"
		device.string = "0"
		device.description = "Built-in Audio"
		module-udev-detect.discovered = "1"
		device.icon_name = "audio-card"
	profiles:
		output:digital-stereo: Digital Stereo Output (priority 5100, available: unknown)
		off: Off (priority 0, available: unknown)
	active profile: <off>
	ports:
		hdmi-output-0: HDMI / DisplayPort (priority 5900, latency offset 0 usec, available: unknown)
			properties:
				device.icon_name = "video-display"
    index: 2
	name: <alsa_card.platform-bcm2835_audio.2>
	driver: <module-alsa-card.c>
	owner module: 8
	properties:
		alsa.card = "1"
		alsa.card_name = "bcm2835 Headphones"
		alsa.long_card_name = "bcm2835 Headphones"
		alsa.driver_name = "snd_bcm2835"
		device.bus_path = "platform-bcm2835_audio"
		sysfs.path = "/devices/platform/soc/fe00b840.mailbox/bcm2835_audio/sound/card1"
		device.form_factor = "internal"
		device.string = "1"
		device.description = "Built-in Audio"
		module-udev-detect.discovered = "1"
		device.icon_name = "audio-card"
	profiles:
		output:analog-stereo: Analog Stereo Output (priority 5100, available: unknown)
		off: Off (priority 0, available: unknown)
	active profile: <output:analog-stereo>
	sinks:
		alsa_output.platform-bcm2835_audio.analog-stereo/#0: Built-in Audio Analog Stereo
	sources:
		alsa_output.platform-bcm2835_audio.analog-stereo.monitor/#1: Monitor of Built-in Audio Analog Stereo
	ports:
		analog-output: Analog Output (priority 9900, latency offset 0 usec, available: unknown)
			properties:

**Comment by Quinny** [comment]
The cards you listed from pacmd have Alsa in the name, I wonder if you need to install RtAudio with alsa support instead?

https://github.com/thestk/rtaudio/blob/4d39e4070e6ce1fda3f26e66a7d72c2caf9bb371/install.txt#L20

**Comment by callimero** [comment]
Hmmm... I thought pulse was the right because it runs on the Raspian. So I compiled for ALSA.

 I think I was also taking the red herring with the "Index", which is totally different in pulse, you your server tells me:

pi@raspberrypi:~/GuitarEffects/web $ sudo ../bin/server 
device ID = 0
device name: hw:bcm2835 HDMI 1,0
: maximum output channels = 8
: maximum input channels = 0
Native format: 2
Sample rate 48000
device ID = 1
device name: hw:bcm2835 Headphones,0
: maximum output channels = 8
: maximum input channels = 0
Native format: 2
Sample rate 48000
device ID = 2
device name: hw:Rocksmith USB Guitar Adapter,0
: maximum output channels = 0
: maximum input channels = 1
Native format: 2
Sample rate 48000
device ID = 3
device name: default
: maximum output channels = 32
: maximum input channels = 32
Native format: 30
Sample rate 48000

So I entered this in main.cpp and I got the visualizer window, hear my guitar and can connect via webbrowser. I see some Buttons (on the page) there. Nothing changes on the signal.

Do I need hardware buttons?

**Comment by callimero** [comment]
So thats what I get in Terminal:

pi@raspberrypi:~/GuitarEffects/web $ sudo ../bin/server 
device ID = 0
device name: hw:bcm2835 HDMI 1,0
: maximum output channels = 8
: maximum input channels = 0
Native format: 2
Sample rate 48000
device ID = 1
device name: hw:bcm2835 Headphones,0
: maximum output channels = 8
: maximum input channels = 0
Native format: 2
Sample rate 48000
device ID = 2
device name: hw:Rocksmith USB Guitar Adapter,0
: maximum output channels = 0
: maximum input channels = 1
Native format: 2
Sample rate 48000
device ID = 3
device name: default
: maximum output channels = 32
: maximum input channels = 32
Native format: 30
Sample rate 48000

RtApiAlsa: dump hardware params just after device open:

ACCESS:  MMAP_INTERLEAVED RW_INTERLEAVED
FORMAT:  U8 S16_LE
SUBFORMAT:  STD
SAMPLE_BITS: [8 16]
FRAME_BITS: [8 128]
CHANNELS: [1 8]
RATE: [8000 192000]
PERIOD_TIME: [10000 16384000]
PERIOD_SIZE: [80 131072]
PERIOD_BYTES: [1024 524288]
PERIODS: [1 128]
BUFFER_TIME: (416 16384000]
BUFFER_SIZE: [80 131072]
BUFFER_BYTES: [1024 131072]
TICK_TIME: ALL

RtApiAlsa: dump hardware params after installation:

ACCESS:  RW_INTERLEAVED
FORMAT:  S16_LE
SUBFORMAT:  STD
SAMPLE_BITS: 16
FRAME_BITS: 16
CHANNELS: 1
RATE: 48000
PERIOD_TIME: (10666 10667)
PERIOD_SIZE: 512
PERIOD_BYTES: 1024
PERIODS: 4
BUFFER_TIME: (42666 42667)
BUFFER_SIZE: 2048
BUFFER_BYTES: 4096
TICK_TIME: 0

RtApiAlsa: dump software params after installation:

tstamp_mode: NONE
tstamp_type: MONOTONIC
period_step: 1
avail_min: 512
start_threshold: 512
stop_threshold: -1
silence_threshold: 0
silence_size: 1073741824
boundary: 1073741824

RtApiAlsa: dump hardware params just after device open:

ACCESS:  MMAP_INTERLEAVED RW_INTERLEAVED
FORMAT:  S16_LE
SUBFORMAT:  STD
SAMPLE_BITS: 16
FRAME_BITS: 16
CHANNELS: 1
RATE: [8000 48000]
PERIOD_TIME: [1000 32768000]
PERIOD_SIZE: [32 262144]
PERIOD_BYTES: [64 524288]
PERIODS: [2 1024]
BUFFER_TIME: (1333 65536000]
BUFFER_SIZE: [64 524288]
BUFFER_BYTES: [128 1048576]
TICK_TIME: ALL

RtApiAlsa: dump hardware params after installation:

ACCESS:  RW_INTERLEAVED
FORMAT:  S16_LE
SUBFORMAT:  STD
SAMPLE_BITS: 16
FRAME_BITS: 16
CHANNELS: 1
RATE: 48000
PERIOD_TIME: (10666 10667)
PERIOD_SIZE: 512
PERIOD_BYTES: 1024
PERIODS: 4
BUFFER_TIME: (42666 42667)
BUFFER_SIZE: 2048
BUFFER_BYTES: 4096
TICK_TIME: 0

RtApiAlsa: dump software params after installation:

tstamp_mode: NONE
tstamp_type: MONOTONIC
period_step: 1
avail_min: 512
start_threshold: 512
stop_threshold: -1
silence_threshold: 0
silence_size: 1073741824
boundary: 1073741824

RtApiAlsa::probeDeviceOpen: unable to synchronize input and output devices.

(2021-09-07 13:36:38) [ERROR   ] Worker Crash: An uncaught exception occurred: std::bad_alloc
(2021-09-07 13:36:38) [ERROR   ] Worker Crash: An uncaught exception occurred: std::bad_alloc
(2021-09-07 13:36:38) [ERROR   ] Worker Crash: An uncaught exception occurred: std::bad_alloc
(2021-09-07 13:36:38) [ERROR   ] Worker Crash: An uncaught exception occurred: std::bad_alloc
frame was too slow
(2021-09-07 13:36:38) [ERROR   ] Worker Crash: An uncaught exception occurred: std::bad_alloc
(2021-09-07 13:36:38) [ERROR   ] Worker Crash: An uncaught exception occurred: std::bad_alloc

**Comment by Quinny** [comment]
Interesting… I haven’t seen that error before

which input/output devices are you using?

**Comment by Quinny** [comment]
I've just added a flow for selecting your input/output device on startup
