### ISSUE TITLE
wiring

### ISSUE THREAD

**Issue by franzhefekranz** [Quinny/GuitarEffects#11]
Could you make some kind of sketch for the wiring, it is kind  of hard to figure out from the photo

**Comment by Quinny** [comment]
I improved the assembly instructions and added a diagram: https://github.com/Quinny/GuitarEffects#setting-up-on-a-raspberry-pi

Does that help?

**Comment by franzhefekranz** [comment]
It helps a lot, but:

GPIO 6 is pin 31
GPIO 12 is pin 32
GPIO 16  is pin 36
GPIO 20 is pin 38
GPIO 21 is pin 40
 
maybe this makes it even more clear.
Thanks a lot.

**Comment by Quinny** [comment]
Added
