### ISSUE TITLE
Building server fails because of missing output directory

### ISSUE THREAD

**Issue by ObscureScience** [Quinny/GuitarEffects#12]
`make server` produces the error `/usr/bin/ld: cannot open output file ./bin/server: No such file or directory`

This is because ./bin does not exist in the repo, and is not created by the Makefile.

creating the directory allows the build to complete.

This was tried on Archlinux, gcc (GCC) 12.2.1 20230216, GNU Make 4.4.1, GNU ld (GNU Binutils) 2.40

**Comment by Quinny** [comment]
Fixed in 18772a1ee0b032719376a49161632749a6755862
