### ISSUE TITLE
Dimensions of the printed casing

### ISSUE THREAD

**Issue by StephanMa** [Quinny/GuitarEffects#15]
Hey there.
Great project!

I am currently trying to print the casing, but it seems that it doesn't fit on my 255mmx255mm bed...
Is this pedal this large?

All the best

**Comment by Quinny** [comment]
![image](https://user-images.githubusercontent.com/4185619/229369209-a0915b77-0081-40af-905d-9a5b1bd05903.jpg)

The case is about 10 inches so its pretty close to 255mm

**Comment by StephanMa** [comment]
Thx!

**Comment by Quinny** [comment]
Sure, when I got mine printed I used https://www.treatstock.com/ and I think i only paid something like $50
