### ISSUE TITLE
Boost io_service has been replaced by io_context

### ISSUE THREAD

**Issue by atzengin** [Quinny/GuitarEffects#8]
Seems it has to be updated accordingly.

> g++ web/main.cpp -lpthread -lboost_system -I crow/include -std=c++1z -I . -I cycfi/Q/q_lib/include -I cycfi/infra/include -Wno-psabi -lrtaudio `sdl2-config --cflags --libs` -o ./bin/server
In file included from crow/include/crow.h:7,
                 from web/main.cpp:8:
crow/include/crow/socket_adaptors.h: In member function ‘boost::asio::io_service& crow::SocketAdaptor::get_io_service()’:
crow/include/crow/socket_adaptors.h:22:28: error: ‘boost::asio::ip::tcp::socket’ {aka ‘class boost::asio::basic_stream_socket<boost::asio::ip::tcp>’} has no member named ‘get_io_service’
   22 |             return socket_.get_io_service();
      |                            ^~~~~~~~~~~~~~
make: *** [Makefile:36: server] Error 1

**Comment by Quinny** [comment]
Thanks for reporting this.

the work around I’ve been using is to manually edit that file and just store and return the ioservice, but that’s pretty hacky.

The right thing is to update the submodule to https://github.com/CrowCpp/Crow

I’ll look into doing this shortly

**Comment by Quinny** [comment]
Should be fixed now
